### PR TITLE
secretconstants file

### PR DESCRIPTION
**Pull request by prashantkhurana**
allows to compile without the file. I have added the file for now, but git will ignore it in future. Change the IAPID and googleIAPCode.

### CODE REVIEW

**Comment by rosenpin** [comment]
Awesome!
Thanks for taking a part of the development!

I'm glad to have help!

**Comment by prashantkhurana** [comment]
Thanks. Minor change : change the file name Secretconstants.properties in SecretConstants to secretconstants.properties (small s). I was doing some testing and forgot to change the name.

**Comment by prashantkhurana** [comment]
Also, my bad. I forced added the secretconstants.propertied file and seems like git is now tracking the file, even though it is asked to ignore. Please try this once and if git does not ignore the file, delete it and create a new one.My bad, didn't know this quirky behavior of git.

**Comment by rosenpin** [comment]
No harm done.
Thank you!
Everything seems to be fine now.

**Pull request merged**
